// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
// const sidebars = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

//   // But you can create a sidebar manually
//   // tutorialSidebar: [
//   //   'index',
//   //   'table_of_content_toc',
//   //   {
//   //     type: 'category',
//   //     label: 'Tutorial',
//   //     items: ['tutorial-basics/create-a-document'],
//   //   },
//   // ],
// };

export default {
  mySidebar: [
    'index',
    'table_of_content_toc',
    'thesis',
    'book_usage',
    {
      type: 'html',
      value: '<hr style="border-top: 1px solid var(--ifm-color-gray-500); margin: 0.5rem 0;" />',
      defaultStyle: true, // Optional: Uses default menu item styles
    },
    'chapters/chapter_01_alerts',
    'chapters/chapter_02_variables_for_strings',
    'chapters/chapter_03_variables_for_numbers',
    'chapters/chapter_04_variable_names_legal_and_illegal',
    'chapters/chapter_05_math_expressions_familiar_operators',
    'chapters/chapter_06_math_expressions_unfamiliar_operators',
    'chapters/chapter_07_math_expressions_eliminating_ambiguity',
    'chapters/chapter_08_concatenating_text_strings',
    'chapters/chapter_09_prompts',
    'chapters/chapter_10_if_statements',
    'chapters/chapter_11_comparison_operators',
    'chapters/chapter_12_if_else_and_else_if_statements',

  //   {
  //     type: 'category',
  //     label: 'Getting Started',
  //     items: [
  //       'introduction', // Refers to docs/introduction.md
  //       'installation', // Refers to docs/installation.md
  //     ],
  //   },
  //   {
  //     type: 'category',
  //     label: 'Guides',
  //     items: [
  //       'guides/usage',
  //       {
  //         type: 'category',
  //         label: 'Advanced',
  //         items: ['guides/advanced/config'],
  //       },
  //     ],
  //   },
  //   {
  //     type: 'link',
  //     label: 'External Link',
  //     href: 'https://example.com',
  //   },
  ],
};
